/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function createLink(options: CrudOptions, input: CreateLinkInput): Promise<LinkResponse>

export interface CreateLinkInput {
  slug?: string
  targetUrl: string
  useMaster?: boolean
}

export interface CrudOptions {
  baseUrl: string
  clientId: string
  apiKey: string
  masterApiKey?: string
}

export interface LinkResponse {
  slug: string
  targetUrl: string
  active: boolean
}

export declare function listLinks(options: CrudOptions, input: ListLinksInput): Promise<Array<LinkResponse>>

export interface ListLinksInput {
  page?: number
  perPage?: number
  slug?: string
  targetContains?: string
  active?: boolean
  createdBefore?: string
  createdAfter?: string
  expiresBefore?: string
  expiresAfter?: string
  useMaster?: boolean
}

export declare function ping(options: CrudOptions, useMaster?: boolean | undefined | null): Promise<void>
